[package]
name = "twinprime"
version = "0.1.3"
authors = ["Elias Sjögreen"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.77.0"
is-prime-for-primitive-int = "0.3.1"

[profile.release]
lto = true
opt-level = 3
